import type { SyncedSource } from "@/lib/ingest/tokens";

export type SourceCompany = {
  slug: string;
  name: string;
  website: string;
  atsSource: SyncedSource;
  /** Board token; several career sites of one company are separated by spaces. See TOKEN_HINT for formats. */
  atsToken: string;
};

type Row = [slug: string, name: string, website: string, token: string];

const rows = (atsSource: SyncedSource, list: Row[]): SourceCompany[] =>
  list.map(([slug, name, website, atsToken]) => ({ slug, name, website, atsSource, atsToken }));

const wd = (host: string, site: string, tenant = host.split(".")[0]!) => `${host}.myworkdayjobs.com|${tenant}|${site}`;

/**
 * Companies hiring in India that publish their openings through a public
 * careers-site API. The sync creates each one on first run; after that the
 * Company row in the database is the source of truth (add or disable feeds
 * from /admin/companies).
 *
 * Every token here was checked against the live API and had India roles.
 */
export const BOOTSTRAP_COMPANIES: SourceCompany[] = [
  ...rows("GREENHOUSE", [
    ["adyen", "Adyen", "https://www.adyen.com", "adyen"],
    ["agoda", "Agoda", "https://www.agoda.com", "agoda"],
    ["airbnb", "Airbnb", "https://www.airbnb.com", "airbnb"],
    ["anaplan", "Anaplan", "https://www.anaplan.com", "anaplan"],
    ["amplitude", "Amplitude", "https://amplitude.com", "amplitude"],
    ["anthropic", "Anthropic", "https://www.anthropic.com", "anthropic"],
    ["capco", "Capco", "https://www.capco.com", "capco"],
    ["celonis", "Celonis", "https://www.celonis.com", "celonis"],
    ["cloudflare", "Cloudflare", "https://www.cloudflare.com", "cloudflare"],
    ["cockroach-labs", "Cockroach Labs", "https://www.cockroachlabs.com", "cockroachlabs"],
    ["coinbase", "Coinbase", "https://www.coinbase.com", "coinbase"],
    ["commvault", "Commvault", "https://www.commvault.com", "commvault"],
    ["coupang", "Coupang", "https://www.coupang.jobs", "coupang"],
    ["databricks", "Databricks", "https://www.databricks.com", "databricks"],
    ["datadog", "Datadog", "https://www.datadoghq.com", "datadog"],
    ["druva", "Druva", "https://www.druva.com", "druva"],
    ["dunnhumby", "dunnhumby", "https://www.dunnhumby.com", "dunnhumby"],
    ["elastic", "Elastic", "https://www.elastic.co", "elastic"],
    ["fastly", "Fastly", "https://www.fastly.com", "fastly"],
    ["figma", "Figma", "https://www.figma.com", "figma"],
    ["fivetran", "Fivetran", "https://www.fivetran.com", "fivetran"],
    ["gitlab", "GitLab", "https://about.gitlab.com", "gitlab"],
    ["glean", "Glean", "https://www.glean.com", "gleanwork"],
    ["grafana-labs", "Grafana Labs", "https://grafana.com", "grafanalabs"],
    ["graphcore", "Graphcore", "https://www.graphcore.ai", "graphcore"],
    ["groww", "Groww", "https://groww.in", "groww"],
    ["hackerrank", "HackerRank", "https://www.hackerrank.com", "hackerrank"],
    ["harness", "Harness", "https://www.harness.io", "harnessinc"],
    ["highradius", "HighRadius", "https://www.highradius.com", "highradius"],
    ["inmobi", "InMobi", "https://www.inmobi.com", "inmobi"],
    ["instawork", "Instawork", "https://www.instawork.com", "instawork"],
    ["karat", "Karat", "https://karat.com", "karat"],
    ["mixpanel", "Mixpanel", "https://mixpanel.com", "mixpanel"],
    ["mongodb", "MongoDB", "https://www.mongodb.com", "mongodb"],
    ["neo4j", "Neo4j", "https://neo4j.com", "neo4j"],
    ["netradyne", "Netradyne", "https://www.netradyne.com", "netradyne"],
    ["netskope", "Netskope", "https://www.netskope.com", "netskope"],
    ["neuraflash", "NeuraFlash", "https://www.neuraflash.com", "neuraflash"],
    ["new-relic", "New Relic", "https://newrelic.com", "newrelic"],
    ["observe-ai", "Observe.AI", "https://www.observe.ai", "observeai"],
    ["okta", "Okta", "https://www.okta.com", "okta"],
    ["pure-storage", "Pure Storage", "https://www.purestorage.com", "purestorage"],
    ["razorpay", "Razorpay", "https://razorpay.com", "razorpaysoftwareprivatelimited"],
    ["roku", "Roku", "https://www.roku.com", "roku"],
    ["rubrik", "Rubrik", "https://www.rubrik.com", "rubrik"],
    ["samsara", "Samsara", "https://www.samsara.com", "samsara"],
    ["sigmoid", "Sigmoid", "https://www.sigmoid.com", "sigmoid"],
    ["singlestore", "SingleStore", "https://www.singlestore.com", "singlestore"],
    ["smartsheet", "Smartsheet", "https://www.smartsheet.com", "smartsheet"],
    ["starburst", "Starburst", "https://www.starburst.io", "starburst"],
    ["stripe", "Stripe", "https://stripe.com", "stripe"],
    ["sumo-logic", "Sumo Logic", "https://www.sumologic.com", "sumologic"],
    ["toast", "Toast", "https://pos.toasttab.com", "toast"],
    ["together-ai", "Together AI", "https://www.together.ai", "togetherai"],
    ["tower-research-capital", "Tower Research Capital", "https://www.tower-research.com", "towerresearchcapital"],
    ["turing", "Turing", "https://www.turing.com", "turing"],
    ["twilio", "Twilio", "https://www.twilio.com", "twilio"],
    ["yugabyte", "Yugabyte", "https://www.yugabyte.com", "yugabyte"],
    ["zenoti", "Zenoti", "https://www.zenoti.com", "zenoti"],
    ["zoominfo", "ZoomInfo", "https://www.zoominfo.com", "zoominfo"],
    ["zscaler", "Zscaler", "https://www.zscaler.com", "zscaler"],
  ]),
  ...rows("LEVER", [
    ["acceldata", "Acceldata", "https://www.acceldata.io", "acceldata"],
    ["ahead", "AHEAD", "https://www.ahead.com", "thinkahead"],
    ["brillio", "Brillio", "https://www.brillio.com", "brillio-2"],
    ["cred", "CRED", "https://cred.club", "cred"],
    ["drivetrain", "Drivetrain", "https://www.drivetrain.ai", "drivetrain"],
    ["fampay", "FamPay", "https://famapp.in", "fampay"],
    ["hevo-data", "Hevo Data", "https://hevodata.com", "hevodata"],
    ["jumpcloud", "JumpCloud", "https://jumpcloud.com", "jumpcloud"],
    ["meesho", "Meesho", "https://www.meesho.com", "meesho"],
    ["mindtickle", "Mindtickle", "https://www.mindtickle.com", "mindtickle"],
    ["moonpay", "MoonPay", "https://www.moonpay.com", "moonpay"],
    ["nium", "Nium", "https://www.nium.com", "nium"],
    ["paytm", "Paytm", "https://paytm.com", "paytm"],
    ["zeta", "Zeta", "https://www.zeta.tech", "zeta"],
    ["zimperium", "Zimperium", "https://www.zimperium.com", "zimperium"],
  ]),
  ...rows("ASHBY", [
    ["astronomer", "Astronomer", "https://www.astronomer.io", "astronomer"],
    ["atlan", "Atlan", "https://atlan.com", "atlan"],
    ["atlys", "Atlys", "https://www.atlys.com", "atlys"],
    ["bolna", "Bolna", "https://www.bolna.ai", "bolna"],
    ["cerebras", "Cerebras", "https://www.cerebras.ai", "cerebras"],
    ["certifyos", "CertifyOS", "https://www.certifyos.com", "certifyos"],
    ["clickhouse", "ClickHouse", "https://clickhouse.com", "clickhouse"],
    ["composio", "Composio", "https://composio.dev", "composio"],
    ["confluent", "Confluent", "https://www.confluent.io", "confluent"],
    ["ema", "Ema", "https://www.ema.co", "ema"],
    ["juniper-square", "Juniper Square", "https://www.junipersquare.com", "junipersquare"],
    ["notion", "Notion", "https://www.notion.so", "notion"],
    ["redis", "Redis", "https://redis.io", "redis"],
    ["sarvam", "Sarvam AI", "https://www.sarvam.ai", "sarvam"],
    ["snowflake", "Snowflake", "https://www.snowflake.com", "snowflake"],
    ["tekion", "Tekion", "https://tekion.com", "tekion"],
    ["thoughtworks", "Thoughtworks", "https://www.thoughtworks.com", "thoughtworks"],
    ["uipath", "UiPath", "https://www.uipath.com", "uipath"],
    ["wisdom-ai", "WisdomAI", "https://www.askwisdom.ai", "Wisdom-AI"],
  ]),
  ...rows("SMARTRECRUITERS", [
    ["arista-networks", "Arista Networks", "https://www.arista.com", "AristaNetworks"],
    ["bosch", "Bosch", "https://www.bosch.in", "BoschGroup"],
    ["canva", "Canva", "https://www.canva.com", "canva"],
    ["cars24", "CARS24", "https://www.cars24.com", "cars24"],
    ["continental", "Continental", "https://www.continental.com", "Continental"],
    ["endava", "Endava", "https://www.endava.com", "endava"],
    ["eurofins", "Eurofins", "https://www.eurofins.com", "Eurofins"],
    ["experian", "Experian", "https://www.experian.com", "experian"],
    ["freshworks", "Freshworks", "https://www.freshworks.com", "Freshworks"],
    ["grab", "Grab", "https://www.grab.com", "Grab"],
    ["hm-group", "H&M Group", "https://hmgroup.com", "HMGroup"],
    ["interviewbit", "InterviewBit", "https://www.interviewbit.com", "interviewbit"],
    ["ixigo", "ixigo", "https://www.ixigo.com", "ixigo"],
    ["linkedin", "LinkedIn", "https://www.linkedin.com", "LinkedIn3"],
    ["lendingkart", "Lendingkart", "https://www.lendingkart.com", "lendingkart"],
    ["nagarro", "Nagarro", "https://www.nagarro.com", "Nagarro1"],
    ["nielseniq", "NielsenIQ", "https://nielseniq.com", "nielseniq"],
    ["qad", "QAD", "https://www.qad.com", "QADInc"],
    ["sandisk", "Sandisk", "https://www.sandisk.com", "Sandisk"],
    ["servicenow", "ServiceNow", "https://www.servicenow.com", "ServiceNow"],
    ["sutherland", "Sutherland", "https://www.sutherlandglobal.com", "Sutherland"],
    ["swiggy", "Swiggy", "https://www.swiggy.com", "swiggy"],
    ["turtlemint", "Turtlemint", "https://www.turtlemint.com", "turtlemint"],
    ["ubisoft", "Ubisoft", "https://www.ubisoft.com", "Ubisoft2"],
    ["unacademy", "Unacademy", "https://unacademy.com", "unacademy"],
    ["upstox", "Upstox", "https://upstox.com", "upstox"],
    ["whatfix", "Whatfix", "https://whatfix.com", "whatfix"],
    ["wabtec", "Wabtec", "https://www.wabteccorp.com", "Wabtec"],
  ]),
  ...rows("EIGHTFOLD", [
    ["bristol-myers-squibb", "Bristol Myers Squibb", "https://www.bms.com", "jobs.bms.com|bms.com"],
    ["microsoft", "Microsoft", "https://www.microsoft.com", "apply.careers.microsoft.com|microsoft.com"],
    ["qualcomm", "Qualcomm", "https://www.qualcomm.com", "careers.qualcomm.com|qualcomm.com"],
    ["vodafone", "Vodafone", "https://www.vodafone.com", "jobs.vodafone.com|vodafone.com"],
  ]),
  ...rows("ORACLE", [
    ["akamai", "Akamai", "https://www.akamai.com", "fa-extu-saasfaprod1.fa.ocs.oraclecloud.com|CX_1|300000000469285"],
    ["bny", "BNY", "https://www.bny.com", "eofe.fa.us2.oraclecloud.com|CX_1001|300000000378365"],
    ["dtcc", "DTCC", "https://www.dtcc.com", "ebxr.fa.us2.oraclecloud.com|CX_1|300000000300092"],
    ["exl", "EXL", "https://www.exlservice.com", "fa-ewjt-saasfaprod1.fa.ocs.oraclecloud.com|CX_2|300000000467203"],
    ["ford", "Ford", "https://www.ford.com", "efds.fa.em5.oraclecloud.com|CX_1|300000000425349"],
    ["fortive", "Fortive", "https://www.fortive.com", "ejta.fa.us6.oraclecloud.com|CX_2001|300000000379610"],
    [
      "goldman-sachs",
      "Goldman Sachs",
      "https://www.goldmansachs.com",
      "hdpc.fa.us2.oraclecloud.com|LateralHiring|300000000228786",
    ],
    [
      "jpmorgan-chase",
      "JPMorgan Chase",
      "https://www.jpmorganchase.com",
      "jpmc.fa.oraclecloud.com|CX_1001|300000000289360",
    ],
    ["oracle", "Oracle", "https://www.oracle.com", "eeho.fa.us2.oraclecloud.com|CX_45001|300000000106947"],
    [
      "zensar",
      "Zensar Technologies",
      "https://www.zensar.com",
      "fa-etvl-saasfaprod1.fa.ocs.oraclecloud.com|CX_1|300000000435151",
    ],
  ]),
  ...rows("AMAZON", [["amazon", "Amazon", "https://www.amazon.jobs", "IND"]]),
  ...rows("WORKDAY", [
    ["3m", "3M", "https://www.3m.com", wd("3m.wd1", "Search")],
    ["abbott", "Abbott", "https://www.abbott.com", wd("abbott.wd5", "abbottcareers")],
    ["accenture", "Accenture", "https://www.accenture.com", wd("accenture.wd103", "AccentureCareers")],
    ["adobe", "Adobe", "https://www.adobe.com", wd("adobe.wd5", "external_experienced")],
    [
      "advance-auto-parts",
      "Advance Auto Parts",
      "https://www.advanceautoparts.com",
      wd("advanceauto.wd5", "AdvanceExternalCareers"),
    ],
    ["agilent", "Agilent", "https://www.agilent.com", wd("agilent.wd5", "Agilent_Careers")],
    ["aig", "AIG", "https://www.aig.com", wd("aig.wd1", "aig")],
    [
      "alliancebernstein",
      "AllianceBernstein",
      "https://www.alliancebernstein.com",
      wd("abglobal.wd1", "alliancebernsteincareers"),
    ],
    ["allstate", "Allstate", "https://www.allstate.com", wd("allstate.wd5", "allstate_careers")],
    ["ameriprise", "Ameriprise Financial", "https://www.ameriprise.com", wd("ameriprise.wd5", "Ameriprise")],
    ["amex-gbt", "Amex GBT", "https://www.amexglobalbusinesstravel.com", wd("travelhrportal.wd1", "Jobs")],
    ["amgen", "Amgen", "https://www.amgen.com", wd("amgen.wd1", "Careers")],
    ["analog-devices", "Analog Devices", "https://www.analog.com", wd("analogdevices.wd1", "External")],
    ["applied-materials", "Applied Materials", "https://www.appliedmaterials.com", wd("amat.wd1", "External")],
    ["aptiv", "Aptiv", "https://www.aptiv.com", wd("aptiv.wd5", "APTIV_CAREERS")],
    ["astrazeneca", "AstraZeneca", "https://www.astrazeneca.com", wd("astrazeneca.wd3", "Careers")],
    ["att", "AT&T", "https://www.att.com", wd("att.wd1", "ATTGeneral")],
    ["athenahealth", "athenahealth", "https://www.athenahealth.com", wd("athenahealth.wd1", "External")],
    ["autodesk", "Autodesk", "https://www.autodesk.com", wd("autodesk.wd1", "Ext")],
    ["availity", "Availity", "https://www.availity.com", wd("availity.wd1", "Availity_Careers_India")],
    ["aveva", "AVEVA", "https://www.aveva.com", wd("aveva.wd3", "AVEVA_careers")],
    ["barclays", "Barclays", "https://home.barclays", wd("barclays.wd3", "External_Career_Site_Barclays")],
    ["barry-wehmiller", "Barry-Wehmiller", "https://www.barrywehmiller.com", wd("barrywehmiller.wd1", "BWCareers")],
    ["baxter", "Baxter", "https://www.baxter.com", wd("baxter.wd1", "baxter")],
    ["bd", "BD", "https://www.bd.com", wd("bdx.wd1", "EXTERNAL_CAREER_SITE_INDIA")],
    ["blackrock", "BlackRock", "https://www.blackrock.com", wd("blackrock.wd1", "BlackRock_Professional")],
    ["blue-yonder", "Blue Yonder", "https://blueyonder.com", wd("jda.wd5", "JDA_Careers")],
    [
      "boeing",
      "Boeing",
      "https://www.boeing.co.in",
      `${wd("boeing.wd1", "EXTERNAL_CAREERS")} ${wd("boeing.wd1", "INTERN")}`,
    ],
    ["broadcom", "Broadcom", "https://www.broadcom.com", wd("broadcom.wd1", "External_Career")],
    ["broadridge", "Broadridge", "https://www.broadridge.com", wd("broadridge.wd5", "Careers")],
    ["browserstack", "BrowserStack", "https://www.browserstack.com", wd("browserstack.wd3", "External")],
    ["cadence", "Cadence", "https://www.cadence.com", wd("cadence.wd1", "External_Careers")],
    ["cardinal-health", "Cardinal Health", "https://www.cardinalhealth.com", wd("cardinalhealth.wd1", "EXT")],
    ["carrier", "Carrier", "https://www.corporate.carrier.com", wd("carrier.wd5", "jobs")],
    ["caterpillar", "Caterpillar", "https://www.caterpillar.com", wd("cat.wd5", "CaterpillarCareers")],
    ["cdk-global", "CDK Global", "https://www.cdkglobal.com", wd("cdk.wd1", "CDK")],
    ["chevron", "Chevron", "https://www.chevron.com", wd("chevron.wd5", "jobs")],
    ["ciena", "Ciena", "https://www.ciena.com", wd("ciena.wd5", "Careers")],
    ["cigna", "Cigna (Evernorth)", "https://www.cigna.com", wd("cigna.wd5", "cignacareers")],
    ["cisco", "Cisco", "https://www.cisco.com", wd("cisco.wd5", "Cisco_Careers")],
    ["citi", "Citi", "https://www.citigroup.com", wd("citi.wd5", "2")],
    ["clarivate", "Clarivate", "https://clarivate.com", wd("clarivate.wd3", "Clarivate_Careers")],
    ["cme-group", "CME Group", "https://www.cmegroup.com", wd("cmegroup.wd1", "cme_careers")],
    ["crowdstrike", "CrowdStrike", "https://www.crowdstrike.com", wd("crowdstrike.wd5", "crowdstrikecareers")],
    ["cubic", "Cubic", "https://www.cubic.com", wd("cubic.wd1", "cubic_global_careers")],
    ["danaher", "Danaher", "https://www.danaher.com", wd("danaher.wd1", "DanaherJobs")],
    ["dentsu", "dentsu", "https://www.dentsu.com", wd("dentsuaegis.wd3", "DAN_GLOBAL")],
    ["deutsche-bank", "Deutsche Bank", "https://www.db.com", wd("db.wd3", "DBWebsite")],
    ["dexcom", "Dexcom", "https://www.dexcom.com", wd("dexcom.wd1", "Dexcom")],
    ["disney", "Disney", "https://www.thewaltdisneycompany.com", wd("disney.wd5", "disneycareer")],
    ["dxc-technology", "DXC Technology", "https://dxc.com", wd("dxctechnology.wd1", "DXCJobs")],
    ["elevance-health", "Elevance Health", "https://www.elevancehealth.com", wd("elevancehealth.wd1", "ANT")],
    ["epicor", "Epicor", "https://www.epicor.com", wd("epicorsoftware.wd5", "epicorjobs")],
    ["equifax", "Equifax", "https://www.equifax.com", wd("equifax.wd5", "External")],
    ["equinix", "Equinix", "https://www.equinix.com", wd("equinix.wd1", "External")],
    ["expedia", "Expedia Group", "https://www.expediagroup.com", wd("expedia.wd108", "search")],
    ["f5", "F5", "https://www.f5.com", wd("ffive.wd5", "f5jobs")],
    ["fico", "FICO", "https://www.fico.com", wd("fico.wd1", "External")],
    ["fidelity-investments", "Fidelity Investments", "https://www.fidelity.com", wd("fmr.wd1", "FidelityCareers")],
    ["fis", "FIS", "https://www.fisglobal.com", wd("fis.wd5", "SearchJobs")],
    ["fiserv", "Fiserv", "https://www.fiserv.com", wd("fiserv.wd5", "EXT")],
    ["flex", "Flex", "https://flex.com", wd("flextronics.wd1", "Careers")],
    ["flutter", "Flutter Entertainment", "https://www.flutter.com", wd("flutterbe.wd3", "Group_External")],
    ["gartner", "Gartner", "https://www.gartner.com", wd("gartner.wd5", "EXT")],
    ["ge-healthcare", "GE HealthCare", "https://www.gehealthcare.com", wd("gehc.wd5", "GEHC_ExternalSite")],
    ["general-motors", "General Motors", "https://www.gm.com", wd("generalmotors.wd5", "Careers_GM")],
    ["genesys", "Genesys", "https://www.genesys.com", wd("genesys.wd1", "Genesys")],
    ["genpact", "Genpact", "https://www.genpact.com", wd("genpact.wd108", "External_Careers")],
    ["global-payments", "Global Payments (TSYS)", "https://www.globalpayments.com", wd("tsys.wd1", "TSYS")],
    ["globalfoundries", "GlobalFoundries", "https://gf.com", wd("globalfoundries.wd1", "External")],
    ["gsk", "GSK", "https://www.gsk.com", wd("gsk.wd5", "GSKCareers")],
    ["guardian-life", "Guardian Life", "https://www.guardianlife.com", wd("guardianlife.wd5", "Guardian-Life-Careers")],
    ["guidehouse", "Guidehouse", "https://guidehouse.com", wd("guidehouse.wd1", "External")],
    ["guidewire", "Guidewire", "https://www.guidewire.com", wd("guidewire.wd5", "external")],
    ["harman", "HARMAN", "https://www.harman.com", wd("harman.wd3", "HARMAN")],
    ["harris-computer", "Harris Computer", "https://www.harriscomputer.com", wd("harriscomputer.wd3", "altera")],
    ["hitachi", "Hitachi", "https://www.hitachi.com", wd("hitachi.wd1", "hitachi")],
    ["hp", "HP", "https://www.hp.com", wd("hp.wd5", "ExternalCareerSite")],
    [
      "hpe",
      "Hewlett Packard Enterprise",
      "https://www.hpe.com",
      `${wd("hpe.wd5", "Jobsathpe")} ${wd("hpe.wd5", "ACJobSite")}`,
    ],
    ["illumina", "Illumina", "https://www.illumina.com", wd("illumina.wd1", "illumina-careers")],
    ["intel", "Intel", "https://www.intel.com", wd("intel.wd1", "External")],
    ["invesco", "Invesco", "https://www.invesco.com", wd("invesco.wd1", "IVZ")],
    ["iqvia", "IQVIA", "https://www.iqvia.com", wd("iqvia.wd1", "iqvia")],
    ["jll", "JLL", "https://www.jll.com", wd("jll.wd1", "jllcareers")],
    ["johnson-controls", "Johnson Controls", "https://www.johnsoncontrols.com", wd("jci.wd5", "JCI")],
    ["kla", "KLA", "https://www.kla.com", wd("kla.wd1", "Search")],
    ["kyndryl", "Kyndryl", "https://www.kyndryl.com", wd("kyndryl.wd5", "kyndrylprofessionalcareers")],
    [
      "lloyds-banking-group",
      "Lloyds Banking Group",
      "https://www.lloydsbankinggroup.com",
      wd("lbg.wd3", "Lloyds_Technology_Centre"),
    ],
    ["lowes", "Lowe's", "https://www.lowes.com", wd("lowes.wd5", "LWS_External_CS")],
    ["lseg", "LSEG", "https://www.lseg.com", wd("lseg.wd3", "Careers")],
    ["maersk", "Maersk", "https://www.maersk.com", wd("maersk.wd3", "Maersk_Careers")],
    ["marsh-mclennan", "Marsh McLennan", "https://www.marshmclennan.com", wd("mmc.wd1", "MMC")],
    ["marvell", "Marvell", "https://www.marvell.com", wd("marvell.wd1", "MarvellCareers")],
    ["mastercard", "Mastercard", "https://www.mastercard.com", wd("mastercard.wd1", "CorporateCareers")],
    ["mckesson", "McKesson", "https://www.mckesson.com", wd("mckesson.wd3", "External_Careers")],
    ["medtronic", "Medtronic", "https://www.medtronic.com", wd("medtronic.wd1", "MedtronicCareers")],
    ["micron", "Micron", "https://www.micron.com", wd("micron.wd1", "External")],
    ["microchip", "Microchip", "https://www.microchip.com", wd("microchiphr.wd5", "external")],
    ["mondelez", "Mondelez International", "https://www.mondelezinternational.com", wd("mdlz.wd3", "External")],
    ["morgan-stanley", "Morgan Stanley", "https://www.morganstanley.com", wd("ms.wd5", "External")],
    [
      "motorola-solutions",
      "Motorola Solutions",
      "https://www.motorolasolutions.com",
      wd("motorolasolutions.wd5", "Careers"),
    ],
    ["msd", "MSD", "https://www.msd.com", wd("msd.wd5", "SearchJobs")],
    ["mufg", "MUFG", "https://www.mufg.jp", wd("mufg.wd3", "MUFG-Careers", "mufgub")],
    ["nasdaq", "Nasdaq", "https://www.nasdaq.com", wd("nasdaq.wd1", "Global_External_Site")],
    ["ncr-atleos", "NCR Atleos", "https://www.ncratleos.com", wd("ncratleos.wd1", "ext_apacatleos")],
    ["ncr-voyix", "NCR Voyix", "https://www.ncrvoyix.com", wd("ncr.wd1", "ext_apac")],
    ["nextgen-healthcare", "NextGen Healthcare", "https://www.nextgen.com", wd("nextgen.wd5", "nextgen_careers")],
    ["nike", "Nike", "https://www.nike.com", wd("nike.wd1", "nke")],
    ["northern-trust", "Northern Trust", "https://www.northerntrust.com", wd("ntrs.wd1", "northerntrust")],
    ["novartis", "Novartis", "https://www.novartis.com", wd("novartis.wd3", "Novartis_Careers")],
    ["nvidia", "NVIDIA", "https://www.nvidia.com", wd("nvidia.wd5", "NVIDIAExternalCareerSite")],
    ["nxp", "NXP Semiconductors", "https://www.nxp.com", wd("nxp.wd3", "careers")],
    ["paypal", "PayPal", "https://www.paypal.com", wd("paypal.wd1", "jobs")],
    ["pfizer", "Pfizer", "https://www.pfizer.com", wd("pfizer.wd1", "PfizerCareers")],
    ["philips", "Philips", "https://www.philips.com", wd("philips.wd3", "jobs-and-careers")],
    ["pitney-bowes", "Pitney Bowes", "https://www.pitneybowes.com", wd("pitneybowes.wd1", "PBCareers")],
    ["procter-gamble", "Procter & Gamble", "https://www.pg.com", wd("pg.wd5", "1000")],
    ["ptc", "PTC", "https://www.ptc.com", wd("ptc.wd1", "PTC")],
    ["pwc", "PwC", "https://www.pwc.in", wd("pwc.wd3", "Global_Experienced_Careers")],
    ["r1-rcm", "R1 RCM", "https://www.r1rcm.com", wd("r1rcm.wd1", "R1RCM")],
    ["red-hat", "Red Hat", "https://www.redhat.com", wd("redhat.wd5", "jobs")],
    ["regal-rexnord", "Regal Rexnord", "https://www.regalrexnord.com", wd("regalrexnord.wd1", "Careers")],
    [
      "relx",
      "RELX (Elsevier, LexisNexis)",
      "https://www.relx.com",
      `${wd("relx.wd3", "relx")} ${wd("relx.wd3", "LexisNexisLegal")}`,
    ],
    ["resmed", "ResMed", "https://www.resmed.com", wd("resmed.wd3", "ResMed_External_Careers")],
    [
      "rockwell-automation",
      "Rockwell Automation",
      "https://www.rockwellautomation.com",
      wd("rockwellautomation.wd1", "External_Rockwell_Automation"),
    ],
    [
      "russell-investments",
      "Russell Investments",
      "https://www.russellinvestments.com",
      wd("russell.wd5", "russellinvestments"),
    ],
    ["sabre", "Sabre", "https://www.sabre.com", wd("sabre.wd1", "SabreJobs")],
    ["sailpoint", "SailPoint", "https://www.sailpoint.com", wd("sailpoint.wd1", "SailPoint")],
    ["salesforce", "Salesforce", "https://www.salesforce.com", wd("salesforce.wd12", "External_Career_Site")],
    ["shell", "Shell", "https://www.shell.com", wd("shell.wd3", "ShellCareers")],
    ["signify", "Signify", "https://www.signify.com", wd("lighting.wd3", "jobs-and-careers")],
    ["smith-nephew", "Smith+Nephew", "https://www.smith-nephew.com", wd("smithnephew.wd5", "External")],
    ["solera", "Solera", "https://www.solera.com", wd("solera.wd5", "Global_Career_Site")],
    ["sp-global", "S&P Global", "https://www.spglobal.com", wd("spgi.wd5", "SPGI_Careers")],
    ["sprinklr", "Sprinklr", "https://www.sprinklr.com", wd("sprinklr.wd1", "careers")],
    ["state-street", "State Street", "https://www.statestreet.com", wd("statestreet.wd1", "Global")],
    ["stryker", "Stryker", "https://www.stryker.com", wd("stryker.wd1", "StrykerCareers")],
    ["synchrony", "Synchrony", "https://www.synchrony.com", wd("synchronyfinancial.wd5", "careers")],
    ["target", "Target", "https://corporate.target.com", wd("target.wd5", "targetcareers")],
    ["td-synnex", "TD SYNNEX", "https://www.tdsynnex.com", wd("synnex.wd5", "tdsynnexcareers")],
    [
      "thermo-fisher",
      "Thermo Fisher Scientific",
      "https://www.thermofisher.com",
      wd("thermofisher.wd5", "ThermoFisherCareers"),
    ],
    [
      "thomson-reuters",
      "Thomson Reuters",
      "https://www.thomsonreuters.com",
      wd("thomsonreuters.wd5", "External_Career_Site"),
    ],
    ["tiaa", "TIAA", "https://www.tiaa.org", wd("tiaa.wd1", "Search")],
    ["transunion", "TransUnion", "https://www.transunion.com", wd("transunion.wd5", "TransUnion")],
    ["trimble", "Trimble", "https://www.trimble.com", wd("trimble.wd1", "TrimbleCareers")],
    ["unisys", "Unisys", "https://www.unisys.com", wd("unisys.wd5", "External")],
    ["vanguard", "Vanguard", "https://www.vanguard.com", wd("vanguard.wd5", "Vanguard_External")],
    [
      "veralto",
      "Veralto",
      "https://www.veralto.com",
      `${wd("veralto.wd1", "HachJobs")} ${wd("veralto.wd1", "eskojobs")}`,
    ],
    ["visa", "Visa", "https://www.visa.co.in", wd("visa.wd5", "Visa")],
    ["walmart", "Walmart Global Tech", "https://tech.walmart.com", wd("walmart.wd504", "WalmartExternal")],
    ["warner-bros-discovery", "Warner Bros. Discovery", "https://www.wbd.com", wd("warnerbros.wd5", "global")],
    ["wells-fargo", "Wells Fargo", "https://www.wellsfargo.com", "wd1.myworkdaysite.com|wf|WellsFargoJobs"],
    ["wex", "WEX", "https://www.wexinc.com", wd("wexinc.wd5", "WEXInc")],
    ["wolters-kluwer", "Wolters Kluwer", "https://www.wolterskluwer.com", wd("wk.wd3", "External")],
    ["workday", "Workday", "https://www.workday.com", wd("workday.wd5", "Workday")],
    ["zebra", "Zebra Technologies", "https://www.zebra.com", wd("zebra.wd501", "Zebra_careers")],
    ["zendesk", "Zendesk", "https://www.zendesk.com", wd("zendesk.wd1", "zendesk")],
  ]),
];
